---
- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    daemon_reload: yes
  when: logstash_service_state != 'stopped' and not logstash_service_output.changed
